# Generated by Selenium IDE
import time
import os
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

class test_widget():
  def setup_method(self, method):
    options = Options()
    cwd = os.getcwd()
    options.add_argument("--headless")
    options.add_argument("--window-size=1280x1500")
    options.add_experimental_option("prefs", {"download.default_directory": cwd})
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def download_widget_image(self):
    self.driver.get("http://localhost:8383/voila/render/example.ipynb")
    time.sleep(3)
    self.driver.save_screenshot("widget-01.png")

test = test_widget()
test.setup_method('Chrome')
test.download_widget_image()
test.teardown_method('Chrome')

