repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: prospector
      language: system
      types: [file, python]
      name: prospector
      description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
      entry: prospector
      exclude: &exclude_files >
          (?x)^(
              docs/source/conf.py|
              setupbase.py
          )$
