#!/bin/bash
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
jupyter labextension install @jupyter-widgets/jupyterlab-manager 
jupyter lab build --dev-build=False --minimize=False
