#!/bin/bash
conda install -y nodejs
pip install --upgrade jupyterlab 
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
jupyter nbextension enable --py widgetsnbextension
jupyter lab build --dev-build=False --minimize=False
