name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt        
          pip freeze

      - name: Run pre-commit
        run:
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: | 
        python -m pip install jupyterlab==2.1.0
        python -m pip install ipywidgets 
    - name: Build the extension
      run: |
        jlpm && jlpm run build
        jupyter labextension install .
        python -m jupyterlab.browser_check
    - name: Check PyPi and NPM version 
      run: | 
        python version_check.py 
